 CREATE TABLE IF NOT EXISTS attendees (
  id INTEGER PRIMARY KEY,
  owner_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
 )